source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Onboarding_Example', :exclusive => true do
  pod "Onboarding", :path => "../"
end

target 'Onboarding_Tests', :exclusive => true do
  pod "Onboarding", :path => "../"

  
end
